#!/bin/sh

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# EDITOR
alias \
 v="$EDITOR" \
 q="exit" \

# tmux
alias \
 t="tmux a || tmux -2" \
 ta="tmux a -t" \
 tl="tmux ls" \

# termux-api
alias \
 tb="termux-brightness" \
 tba="termux-brightness auto" \
 tbl="termux-brightness 25" \
 tbh="termux-brightness 100" \
 to="termux-open" \



## Files
# Operation
alias \
 ls="eza --colour=auto --group-directories-first --icons=auto" \
 la="eza -l --colour=auto --group-directories-first --icons=auto --no-filesize --no-time --no-permissions --no-user" \
 lah="eza -la --colour=auto --group-directories-first --icons=auto" \
 cd="z" \
 ..="cd .." \
 cp="cp -v" \
 mv="mv -v" \
 rm="rm -v" \
 rm1="rm -v 1*" \
 mkd="mkdir -pv" \
 cat="bat"
 diff="batdiff"


# Navigation
alias \
 rp="cd $PREFIX" \
 rpe="cd $PREFIX/etc/" \
 rpb="cd $PREFIX/bin/" \
 rps="cd $PREFIX/share/" \
 rpt="cd $PREFIX/tmp/" \
 xcc="cd $XDG_CACHE_HOME" \
 xc="cd $XDG_CONFIG_HOME" \
 zd="cd $ZDOTDIR" \
 xcs="cd $XDG_CONFIG_HOME/shellrc" \
 xcv="cd $HOME/.config/vimwiki" \
 xcvn="cd $HOME/.config/vimwiki/notes" \
 xcvcnf="cd $HOME/.config/vimwiki/cnf" \
 jamuna="cd $HOME/.config/vimwiki/cnf/jamuna" \
 saif="cd $HOME/.config/vimwiki/cnf/saif" \
 ssaf="cd $HOME/.config/vimwiki/cnf/ssaf" \
 xd="cd $XDG_DATA_HOME" \
 dlb="cd $HOME/.local/bin" \
 dlbs="cd $HOME/.local/bin/scripts" \
 h="cd $HOME" \
 hc="cd $HOME/cnf" \
 hd="cd $HOME/storage/downloads/" \
 hdc="cd $HOME/storage/downloads/cnf" \
 hdcl="cd $HOME/storage/downloads/cnf/cnflem" \
 hn="cd $HOME/storage/shared/Documents/" \
 hsd="cd $HOME/storage/shared/" \
 htui="cd $HOME/storage/shared/t-ui" \
 htmp="cd $HOME/tmp" \
 ht="cd $HOME/termux" \
 fv="$EDITOR $XDG_CONFIG_HOME/nvim/init.vim" \
 fz="$EDITOR $ZDOTDIR/.zshrc" \
 fa="$EDITOR $XDG_CONFIG_HOME/shellrc/aliasrc" \
 fzfn="$EDITOR $XDG_CONFIG_HOME/shellrc/zshfnrc" \
 fzp="$EDITOR $HOME/.profile" \

# db
alias \
 updb="updatedb" \

## Info
alias \
 pdw="pwd" \
 free="free -mt" \
 diff="diff --color=auto" \
 df="df -h" \
 grep="grep --color=auto" \
 egrep="egrep --color=auto" \
 fgrep="fgrep --color=auto" \

## Package
# pkg
alias \
 up="apt update && pkg upgrade" \
 inp="apt install" \
 rmv="apt remove" \
 armv="apt autoremove" \
 pacs="apt search" \

# c source
alias \
    cinp="make install" \
    crmv="make uninstall" \

# Python/pip
alias \
 pipup="pip-review -i" \
 pipinp="pip install -U" \
 pip3inp="pip3 install" \
 piprmv="pip uninstall" \

# MAIL/mutt-wizard
alias \
 pnl="pass nlogin" \
 ibx="mutt" \
 mail="mw -Y; mutt" \
 mp="mw -y mparvz@gmail.com; mutt" \
 ib="mw -y imrufbd@gmail.com; mutt" \
 rry="mw -y riponridwan@yahoo.com; mutt" \
 lic="mw -y riprid@cock.li; mutt" \

# pass
alias \
 gpc="pass -c" \

# Game/SolVitaire
# alias doku="nudoku”
alias \
 tet="tetris" \
 frcl="cd ~/games/sol; ./freecell; cd" \
 sol="cd ~/games/sol; ./sol; cd" \
 spider="cd ~/games/sol; ./spider; cd" \
 mine="cd ~/games/mines; ./mines; cd" \

## Network
# IP/PING
alias \
 pn="ping -c 3 google.com" \
 myip="ifconfig" \
 isp="curl ifconfig.co" \

# SSH #http #ftpu ftp_server zsh function
alias \
 sfu="sshd" \
 sfd="pkill sshd" \
 ftpu="ftp_server" \
 httpu="python ~/.local/bin/scripts/shsu.py" \
 httpmu="python ~/.local/bin/scripts/shsumu.py" \
 at="artix_ssh" \
 art="sshpass -p jj ssh masud@192.168.31.13" \
 viv="sshpass -p jj ssh masud@192.168.43.145" \

# zsh function
# fzf/surfraw
alias \
 fo="fzf_to" \
 fe="fzf_file" \
 ff="fzf_cd" \
 fh="fzf_history" \
 fk="fzf_kill" \
 fs="fzf_sr" \
 fbm="fzf_srbr" \

# Services/ More at chubin/awesome-console-servies
alias \
 ispc="curl ifconfig.co/country" \
 ispct="curl ifconfig.co/city" \
 geo="curl ip-api.com" \
 lsu="ttm_url_shorten" \
 weather="curl wttr.in/khagrachari" \
 odic="online_dic" \
 oman="online_man" \

## Downloader
# wget/aria2
alias \
 wget="wget -c" \
 a2="aria2c" \
 a2p="aria2p" \
 a2s="a2pd start" \
 a2d="a2pd stop" \

# yt-dlp
alias \
 ytd-aac="yt-dlp --extract-audio --audio-format aac" \
 ytd-besta="yt-dlp --extract-audio --audio-format best" \
 ytd-flac="yt-dlp --extract-audio --audio-format flac" \
 ytd-m4a="yt-dlp --extract-audio --audio-format m4a" \
 ytd-mp3="yt-dlp --extract-audio --audio-format mp3" \
 ytd-opus="yt-dlp --extract-audio --audio-format opus" \
 ytd-vorbis="yt-dlp --extract-audio --audio-format vorbis" \
 ytd-wav="yt-dlp --extract-audio --audio-format wav" \
 ytd-best="yt-dlp -f bestvideo+bestaudio" \
 ytd="yt-dlp" \
 ytdF="yt-dlp -F" \
 ytdf="yt-dlp -f" \
 ytdic="yt-dlp --ignore-config" \
 ytv="youtube-viewer -C" \
 ytm="ytfzf -m" \

# TRANSMISSION
alias \
 pfx="peerflix -k -f /data/data/com.termux/files/home/Downloads" \
 tfx="torrentflix" \

# MIS
alias \
 math="mathomatic" \
 o="qalc" \
 pc="python -ic 'from __future__ import division; from math import *; from sympy import symbols, Eq, solve; from random import *'" \
 c2="units" \
 sw="termdown" \
 rt="tuir" \
 el="elinks" \
 m="ncmpcpp" \
 r="radio" \
 def="sdcv" \
 keep="keepcli" \
 eq="pnglatex -b Transparent -p amssymb:amsmath -d 300 -s 12 -o eq.png" \

# GIT
alias \
 gitc="git clone" \
 gitu="git push -u origin main" \
 gitd="git pull" \
 gitca="git commit -a" \
 gitcm="git commit -m" \
 gita="git add" \
 gits="git status" \

 
# ARCHIVE
alias \
 uzp="atool -x" \
 zp="apack" \

