#!/bin/sh

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# EDITOR
alias \
 v="$EDITOR" \
 q="exit" \

#tmux
alias \
 t="tmux" \
 tl="tmux ls" \
 ta0="tmux attach-session -t 0" \
 ta="tmux attach-session -t" \

# Files
alias \
 ls="ls --color=auto --group-directories-first" \
 lah="exa -la --color=auto --group-directories-first" \
 ..="cd .." \
 cp="cp -v" \
 mv="mv -v" \
 rm="rm -v" \
 rm1="rm -v 1*" \
 mkd="mkdir -pv" \

#db
alias \
 updb="updatedb" \
 e="fzf_file" \
 f="fzf_cd" \
 h="fzf_history" \
 k="fzf_kill" \
 s="fzf_sr" \
 bm="fzf_srbr" \

#termux-api
alias \
 tb="termux-brightness" \
 tba="termux-brightness auto" \
 tbl="termux-brightness 25" \
 tbh="termux-brightness 100" \
 ts="termux-style" \
 to="termux-open" \
 tp="termux-open 1.jpg" \
 tg="termux-open 1.gif" \
 tv="termux-open 1.mp4" \

#APT
alias \
 up="apt update && apt upgrade" \
 inp="apt install" \
 rmv="apt remove" \
 armv="apt autoremove" \
 pacs="apt search" \

#youtube-dl
alias \
 ytd-aac="youtube-dl --extract-audio --audio-format aac" \
 ytd-besta="youtube-dl --extract-audio --audio-format best" \
 ytd-flac="youtube-dl --extract-audio --audio-format flac" \
 ytd-m4a="youtube-dl --extract-audio --audio-format m4a" \
 ytd-mp3="youtube-dl --extract-audio --audio-format mp3" \
 ytd-opus="youtube-dl --extract-audio --audio-format opus" \
 ytd-vorbis="youtube-dl --extract-audio --audio-format vorbis" \
 ytd-wav="youtube-dl --extract-audio --audio-format wav" \
 ytd-best="youtube-dl -f bestvideo+bestaudio" \
 ytd="youtube-dl" \
 ytdF="youtube-dl -F" \
 ytdf="youtube-dl -f" \
 ytdic="youtube-dl --ignore-config" \
 ytv="youtube-viewer -C" \

#MUTT
alias \
 ibx="mutt" \
 mail="mw -Y; mutt" \
 mp="mw -y mparvz@gmail.com; mutt" \
 ib="mw -y imrufbd@gmail.com; mutt" \
 rry="mw -y riponridwan@yahoo.com; mutt" \
 lic="mw -y riprid@cock.li; mutt" \

#GIT
alias \
 gitc="git clone" \
 gitu="git push -u origin master" \
 gitca="git commit -a" \
 gita="git add" \
 gits="git status" \

#pass
alias \
 gpc="pass -c" \


#Game
#alias doku="nudoku”
alias \
 tet="tetris" \
 frcl="cd ~/games/sol; ./freecell; cd" \
 sol="cd ~/games/sol; ./sol; cd" \
 spider="cd ~/games/sol; ./spider; cd" \

#SSH #http #ftpu busybox script
alias \
 sfu="sshd" \
 sfd="pkill sshd" \
 httpu="python3 ~/.scripts/shsu.py" \


#ip/ping
alias \
 pnet="ping -c 3 google.com" \
 myip="ifconfig" \
 isp="curl ifconfig.co" \
 ip="ip addr show" \
 ns="speedtest" \
 nss="speedtest --simple --single" \

#tfx-pfx
alias \
 pfx="peerflix -k -f /home/masud/Videos/ptfx" \
 tfx="torrentflix" \

#downloader
alias \
 wget="wget -c" \
 a2="aria2c" \
 a2p="aria2p" \
 a2s="a2pd start" \
 a2d="a2pd stop" \

#MIS
alias \
 weather="curl wttr.in/khagrachari" \
 math="mathomatic" \
 pc="python -ic 'from __future__ import division; from math import *; from random import *'" \
 c2="units" \
 sw="termdown" \
 rt="tuir" \
 el="elinks" \
 m="cmus" \
 def="sdcv" \
 keep="keepcli" \
 covid="curl https://corona-stats.online?source=2" \
 eq="pnglatex -b Transparent -p amssymb:amsmath -d 300 -s 12 -o eq.png" \

#Info
alias \
 pdw="pwd" \
 free="free -mt" \
 diff="diff --color=auto" \
 df="df -h" \
 grep="grep --color=auto" \
 egrep="egrep --color=auto" \
 fgrep="fgrep --color=auto" \
