#!/usr/bin/env bash


url="$*"

echo "Fetching available formats for $url..."
youtube-dl -F "$url"
read -p "Please enter the desired quality code: " FORMAT

echo "Streaming with quality $FORMAT..."
xdg-open $(youtube-dl -f $FORMAT -g "$url")
